abbreviations_fr = {
    "$" : " dollar ",
    "€" : " euro ",
    "a.m" : "avant midi",
    "afk" : "absent",
    "app" : "application",
    "approx" : "approximativement",
    "apps" : "applications",
    "asap" : "le plus vite possible",
    "ave." : "avenue",
    "b2b" : "business to business",
    "b2c" : "business to customer",
    "bae" : "before anyone else",
    "bros" : "freres",
    "btw" : "au fait",
    "cf" : "se reporter à ",
    "cia" : "central intelligence agency",
    "cv" : "curriculum vitae",
    "dm" : "message privé",
    "faq" : "questions les plus posées",
    "fb" : "facebook",
    "ft." : "feet",
    "ft" : "featuring",
    "gg" : "bien joué",
    "gl" : "bonne chance",
    "glhf" : "bon jeu et bonne chance",
    "IG" : "instagram",
    "mdr" : "mort de rire",
    "mdrr" : "mort de rire",
    "mdrrr" : "mort de rire",
    "ptdr" : "pété de rire",
    "nsfw" : "not safe for work",
    "omg" : "oh mon Dieu",
    "p.m" : "aprés midi",
    "pov" : "point de vue",
    "ps" : "postscript",
    "w/" : "avec",
    "w/o" : "sans",
    "wtf" : "what the fuck",
    "yd" : "yard",
    "zzz" : "dormir ennuyé et fatigué",
    "mm" : "même",
    "tt" : "tout",
    "bi1" : "bien",
    "a+" : "à plus tard",
    "bjr" : "bonjour",
    "bsr" : "bonsoir",
    "stp" : "s'il te plait"
}